#pragma once

#include <wfc/logger.hpp>

#define LOG_NAME "PrefixDB"
#define PREFIXDB_LOG(TYPE, X)    WFC_WRITE_LOG(LOG_NAME, TYPE, X)
#define PREFIXDB_LOG_REPLI(ON, X) if (ON) { PREFIXDB_LOG("REPLI", X)}
#define PREFIXDB_LOG_ERROR(X)    WFC_LOG_ERROR( LOG_NAME, X )
#define PREFIXDB_LOG_WARNING(X)  WFC_LOG_WARNING( LOG_NAME, X )
#define PREFIXDB_LOG_MESSAGE(X)  WFC_LOG_MESSAGE( LOG_NAME, X )
#define PREFIXDB_LOG_FATAL(X)    WFC_LOG_FATAL( LOG_NAME, X )
#define PREFIXDB_LOG_BEGIN(X)    WFC_LOG_BEGIN( LOG_NAME, X )
#define PREFIXDB_LOG_END(X)      WFC_LOG_END( LOG_NAME, X )
#define PREFIXDB_LOG_DEBUG(X)    WFC_LOG_DEBUG( LOG_NAME, X )
#define PREFIXDB_LOG_TRACE(X)    WFC_LOG_TRACE( LOG_NAME, X )
#define PREFIXDB_LOG_PROGRESS(X) WFC_LOG_PROGRESS( NAME, X )


